apiVersion: apps/v1
kind: Deployment
metadata:
  name: snippetbox
  namespace: workloads
spec:
  replicas: 3
  selector:
    matchLabels:
      app: snippetbox
  template:
    metadata:
      labels:
        app: snippetbox
    spec:
      containers:
      - name: snippetbox
        image: localhost:5001/snippetbox:latest
        command: ["./web"]
        args:
        - "-dsn"
        - "root:example@/snippetbox?parseTime=true" 
        ports:
        - containerPort: 4000
        env:
        - name: addr
          value: :4000
        - name: dsn
          value: root:example@/snippetbox?parseTime=true
---
apiVersion: v1
kind: Service
metadata:
  name: snippetbox
  namespace: workloads
spec:
  selector:
    app: snippetbox
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: ClusterIP