apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: snippetbox
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "snippetbox-{{metadata.labels.name}}"
    spec:
      destination:
        namespace: workloads
        server: "{{server}}"
      project: default
      source:
        path: kubernetes/manifests
        repoURL: https://github.com/jbutcher93/snippetbox
        targetRevision: main
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: false